blueprint:
  name: Aqara Mini Switch - Multi Press
  description: |
    Trigger different actions based on single, double, or long press from a button entity.
    This blueprint works with buttons that report press types in the 'event_type' attribute.
  domain: automation
  input:
    button_event:
      name: Button Event
      description: The button entity (event domain) to monitor.
      selector:
        entity:
          domain: event

    single_press_action:
      name: Action on Single Press
      selector:
        action: {}

    double_press_action:
      name: Action on Double Press
      selector:
        action: {}

    long_press_action:
      name: Action on Long Press
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input button_event

mode: single

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.event_type == 'single_press' }}"
        sequence: !input single_press_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.event_type == 'double_press' }}"
        sequence: !input double_press_action

      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.attributes.event_type == 'long_press' }}"
        sequence: !input long_press_action
